### ISSUE TITLE
inconsistent tensor size error

### ISSUE THREAD

**Issue by AlphaGoMK** [yeezhu/SPN.pytorch#21]
When I run `bash runme.sh`, I encounter the exception below.

Traceback (most recent call last):
  File "/home/mukai/anaconda3/envs/py3.5/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/mukai/anaconda3/envs/py3.5/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/mukai/SPN.pytorch/demo/experiment/demo_voc2007.py", line 63, in <module>
    main_voc2007()
  File "/home/mukai/SPN.pytorch/demo/experiment/demo_voc2007.py", line 59, in main_voc2007
    engine.multi_learning(model, criterion, train_dataset, val_dataset)
  File "/home/mukai/SPN.pytorch/demo/experiment/engine.py", line 108, in multi_learning
    state_dicts.append(self.learning(model, criterion, train_dataset, val_dataset, optimizer)) 
  File "/home/mukai/SPN.pytorch/demo/experiment/engine.py", line 184, in learning
    self.train(train_loader, model, criterion, optimizer, epoch)
  File "/home/mukai/SPN.pytorch/demo/experiment/engine.py", line 211, in train
    for i, (input, target) in enumerate(data_loader):
  File "/home/mukai/anaconda3/envs/py3.5/lib/python3.5/site-packages/tqdm/_tqdm.py", line 862, in __iter__
    for obj in iterable:
  File "/home/mukai/anaconda3/envs/py3.5/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 212, in __next__
    return self._process_next_batch(batch)
  File "/home/mukai/anaconda3/envs/py3.5/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 239, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "/home/mukai/anaconda3/envs/py3.5/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 41, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/mukai/anaconda3/envs/py3.5/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 41, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/mukai/SPN.pytorch/demo/experiment/voc.py", line 247, in __getitem__
    img = self.transform(img)
  File "/home/mukai/anaconda3/envs/py3.5/lib/python3.5/site-packages/torchvision/transforms.py", line 34, in __call__
    img = t(img)
  File "/home/mukai/SPN.pytorch/demo/experiment/engine.py", line 120, in <lambda>
    lambda x: x - torch.Tensor(model.image_normalization_mean).view(3, 1, 1),
  File "/home/mukai/anaconda3/envs/py3.5/lib/python3.5/site-packages/torch/tensor.py", line 274, in __sub__
    return self.sub(other)
RuntimeError: inconsistent tensor size at /opt/conda/conda-bld/pytorch_1501969512886/work/pytorch-0.1.12/torch/lib/TH/generic/THTensorMath.c:831

It may send a inconsistent tensor to the function `enumerate(data_loader)`.
I don't know how to fix it.
Hope your help.

**Comment by yeezhu** [comment]
@AlphaGoMK  
Please try pytorch 0.3.0

**Comment by AlphaGoMK** [comment]
@yeezhu 
thanks, my problem solved after update pytorch to torch-0.3.0
